#!/bin/bash

tag=alpine-mysql

if [ -n "$1" ];
then
    tag=$1
fi


if [ -f "$PWD/.as/docker-registry" ];
then
    docker_registry=`cat $PWD/.as/docker-registry`
    docker tag $docker_registry:$tag $docker_registry:mysql
    docker tag $docker_registry:$tag $docker_registry:4.8.3-mysql
    docker tag $docker_registry:$tag $docker_registry:4.8.3-alpine-mysql
    docker tag $docker_registry:$tag $docker_registry:4.8.3-alpine-3.19-mysql
    docker push $docker_registry:$tag
    docker push $docker_registry:mysql
    docker push $docker_registry:4.8.3-mysql
    docker push $docker_registry:4.8.3-alpine-mysql
    docker push $docker_registry:4.8.3-alpine-3.19-mysql
else
    echo "Could not find a Docker registry URL file at $PWD/.as/docker-registry"
    exit 1
fi

exit
